# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G

loom.platform=neoforge

versionMc=1.21.1
versionForge=21.1.208
versionLoaderUpstream=0.17.2
versionYarn=1.21.1+build.3
